// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2JsGK3yTTZwboW7oCmdFtah3ulyZEGVo',
    appId: '1:578887992559:web:81df55018da8e3f627071a',
    messagingSenderId: '578887992559',
    projectId: 'shopapp-7c5c8',
    authDomain: 'shopapp-7c5c8.firebaseapp.com',
    storageBucket: 'shopapp-7c5c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKn0LZUdWfigVi3PqGdp9qiwUZJ57ThXs',
    appId: '1:578887992559:android:5220ede73bc4fe8e27071a',
    messagingSenderId: '578887992559',
    projectId: 'shopapp-7c5c8',
    storageBucket: 'shopapp-7c5c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK3eAkREEjunv4oHczELmiq9GXeUPmQXw',
    appId: '1:578887992559:ios:6d6e32b5cef1ad5a27071a',
    messagingSenderId: '578887992559',
    projectId: 'shopapp-7c5c8',
    storageBucket: 'shopapp-7c5c8.appspot.com',
    iosBundleId: 'com.example.firebaseSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK3eAkREEjunv4oHczELmiq9GXeUPmQXw',
    appId: '1:578887992559:ios:21dc0b63a05b9efe27071a',
    messagingSenderId: '578887992559',
    projectId: 'shopapp-7c5c8',
    storageBucket: 'shopapp-7c5c8.appspot.com',
    iosBundleId: 'com.example.firebaseSetup.RunnerTests',
  );
}
